services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  gateway:
    build:
      context: .
      dockerfile: gozon.apigateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - orders-service
      - payments-service

  orders-service:
    build:
      context: .
      dockerfile: gozon.services.orders/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=orders_db;Username=postgres;Password=password"
      RabbitMq__Host: "rabbitmq"
      ASPNETCORE_ENVIRONMENT: "Development" 
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5001:8080"

  payments-service:
    build:
      context: .
      dockerfile: gozon.services.payments/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=payments_db;Username=postgres;Password=password"
      RabbitMq__Host: "rabbitmq"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5002:8080"

  frontend:
    build:
      context: .
      dockerfile: gozon.frontend/Dockerfile
    ports:
      - "5003:8080" 
    environment:
      GatewayUrl: "http://gateway:8080"
    depends_on:
      - gateway